using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PallesGavebodWebApp.Models;

namespace PallesGavebodWebApp.api
{
	[Produces("application/json")]
	[Route("api/[controller]")]
    [ApiController]
    public class GiftsController : ControllerBase
    {
        private readonly MainDbContext _context;

        public GiftsController(MainDbContext context)
        {
            _context = context;
        }

		/// <summary>
		/// Returns all gifts from the database
		/// </summary>
		// GET: api/Gifts
		[HttpGet]
        public async Task<ActionResult<IEnumerable<Gift>>> GetGifts()
        {
            return await _context.Gifts.ToListAsync();
        }

		/// <summary>
		/// Returns all gifts that are only for a specified gender
		/// The method only checks for the input parameter string "girl", if it is not, then return a list of gifts for boys, else for girls
		/// </summary>
		/// <param name="gender">if the input string is "girl", then return a list of gifts only for girls, else for boys</param>
		// GET: api/Gifts
		[HttpGet("OnlyFor/{gender}")]
		public async Task<ActionResult<IEnumerable<Gift>>> GetGiftsForGenderOnly(string gender)
		{
			if(gender == "girl")
			{
				return await _context.Gifts
					.Where(gift => gift.GirlGift == true && gift.BoyGift == false)
					.ToListAsync();
			}

			return await _context.Gifts
				.Where(gift => gift.GirlGift == false && gift.BoyGift == true)
				.ToListAsync();
		}

		/// <summary>
		/// Returns the gift where the input is equal to the gift number.
		/// </summary>
		/// <param name="id">Gift Number</param>
		// GET: api/Gifts/5
		[HttpGet("{id}")]
        public async Task<ActionResult<Gift>> GetGift(int id)
        {
            var gift = await _context.Gifts.FindAsync(id);

            if (gift == null)
            {
                return NotFound();
            }

            return gift;
        }

		/// <summary>
		/// Updates the gift where input id is equal to the gift number stored in the database.
		/// </summary>
		/// <param name="id">Gift number</param>
		/// <param name="gift">The gift object that contains the updated information</param>
        // PUT: api/Gifts/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutGift(int id, Gift gift)
        {
            if (id != gift.GiftNumber)
            {
                return BadRequest();
            }

            _context.Entry(gift).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GiftExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

		/// <summary>
		/// Add a gift to the database.
		/// </summary>
		/// <param name="gift">Gift object to store in the database</param>
		/// <remarks>The api call stores when the gift is created in the CreationDate property. The GiftNumber property is generated by the Entity Framework.</remarks>
		// POST: api/Gifts
		[HttpPost]
        public async Task<ActionResult<Gift>> PostGift(Gift gift)
        {
			gift.CreationDate = DateTime.Now;

            _context.Gifts.Add(gift);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetGift", new { id = gift.GiftNumber }, gift);
        }

		/// <summary>
		/// Deletes the gift from the database if the input id is equal to a GiftNumber in the database.
		/// </summary>
		/// <param name="id">Gift Number</param>
        // DELETE: api/Gifts/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Gift>> DeleteGift(int id)
        {
            var gift = await _context.Gifts.FindAsync(id);
            if (gift == null)
            {
                return NotFound();
            }

            _context.Gifts.Remove(gift);
            await _context.SaveChangesAsync();

            return gift;
        }

        private bool GiftExists(int id)
        {
            return _context.Gifts.Any(e => e.GiftNumber == id);
        }
    }
}
